symfonyProject/src/Entity/Horaire.php
<?php

namespace App\Entity;

use App\Repository\HoraireRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HoraireRepository::class)
 */
class Horaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Sport::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $idSport;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Jour;

    /**
     * @ORM\Column(type="string")
     */
    private $Heure;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdSport(): ?Sport
    {
        return $this->idSport;
    }

    public function setIdSport(?Sport $idSport): self
    {
        $this->idSport = $idSport;

        return $this;
    }

    public function getJour(): ?string
    {
        return $this->Jour;
    }

    public function setJour(string $Jour): self
    {
        $this->Jour = $Jour;

        return $this;
    }

    public function getHeure(): ?string
    {
        return $this->Heure;
    }

    public function setHeure(string $Heure): self
    {
        $this->Heure = $Heure;

        return $this;
    }

    public function __toString(){
        return " n° $this->id -- $this->idSport -- $this->Jour -- $this->Heure";
    }

}

symfonyProject/src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Sport;
use App\Entity\Horaire;
use App\Entity\User;
use App\Entity\Commandes;
use App\Entity\Reservations;

use Symfony\Component\HttpFoundation\Session\SessionInterface;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index( SessionInterface $session): Response
    {
        $panier= $session->get('panier', []);
        return $this->render('default/index.html.twig');
    }


    /**
     * @Route("/sports", name="AllSports")
     */
    public function AllSports()
    {
        $AllSports = $this->getDoctrine()->getRepository(Sport::class)->findAll();
        return $this->render('default/sports.html.twig', [
            'AllSports' => $AllSports,
        ]);
    }

   

     /**
     *@Route("/planning/{id}",requirements={"id":"\d"}, name="planning")
     */
    public function planning($id)
    {
        $horaires = $this->getDoctrine()->getRepository(Horaire::class)->findByIdSport($id);
        $sport = $this->getDoctrine()->getRepository(Sport::class)->find($id);
        return $this->render('default/planning.html.twig', [
            'horaires' => $horaires,
            'sport'=> $sport,
        ]);
    }


    /**
     *@Route("/profil/{idUser}",requirements={"idUser":"\d"}, name="profil")
     */
    public function profil($idUser)
    {
        $user = $this->getDoctrine()->getRepository(User::class)->find($idUser);
        $CommandeUser = $this->getDoctrine()->getRepository(Commandes::class)->findByIdUser($idUser);
        $ttLesReservations=[];
        foreach($CommandeUser as $commande){
            $ttLesReservations[]=$this->getDoctrine()->getRepository(Reservations::class)->findByIdCommande($commande->getId());
        }
        return $this->render('default/profil.html.twig', [
            'user' => $user,
            'reservations'=> $ttLesReservations,
            'commandes'=>$CommandeUser
        ]);
    }


     
}

symfonyProject/templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}

<header class="index">
<div>

<h1> Sport Escape </h1>

<ul> 

<li> <a href="{{ path('home')}}"> Accueil </a> </li>
<li> <a href="{{ path('AllSports')}}"> Voir les sports </a> </li>
<li> <a href="{{ path('panier_index')}}">Votre panier</a> </li>
{% if not app.user %}
<li> <a href="{{ path('security_login')}}">  Se connecter  </a> </li>
 <li><a href="{{ path('security_registration')}}">  Creer un compte </a> </li> 
{% else %}
<li> <a href="{{ path('profil', {'idUser': app.user.id } )}}">Votre profil</a> </li>
<li> <a href="{{ path('security_logout')}}"> Se deconnecter  </a> </li>
{% endif %}
</ul>
 </div>


</header>

<div class="imagesSilhouette1"> 
    <img src="{{ asset( 'img/volleyball-310770_640.png' )}}" alt="sport" class="imgVolley">
</div>

    <section class=" principale">

        <div class="info">

        Tous nos cours sont à 30 €, profitez d'une activité sportive dans une ambiance chaleureuse ! 


           

        </div>

    </section>
<div class="imagesSilhouette2"> 
    <img src="{{ asset( 'img/volleyball-310328_640.png ' )}}" alt="sport" >
</div>
    



    <footer> 
        <p> Ce site est un projet purement personnel d'entrainement au framework Symfony </p>
        <p> This is a fully personnal project made for training the Symfony framework</p>
         <a href="{{ path('admin')}}">  Administration  </a>

    </footer>





{% endblock %}

symfonyProject/templates/default/planning.html.twig
{% extends 'base.html.twig' %}

{% block title %}Planning{% endblock %}

{% block body %}


<header  class="secondary">
<div>

<h1> Sport Escape </h1>

<ul> 

<li> <a href="{{ path('home')}}"> Accueil </a> </li>
<li> <a href="{{ path('AllSports')}}"> Voir les sports </a> </li>
<li> <a href="{{ path('panier_index')}}">Votre panier</a> </li>
{% if not app.user %}
<li> <a href="{{ path('security_login')}}">  Se connecter  </a> </li>
 <li><a href="{{ path('security_registration')}}">  Creer un compte </a> </li> 
{% else %}
<li> <a href="{{ path('profil', {'idUser': app.user.id } )}}">Votre profil</a> </li>
<li> <a href="{{ path('security_logout')}}"> Se deconnecter  </a> </li>
{% endif %}
</ul>
 </div>


</header>




<section class="sectionPlanning"> 

<h1 class ="planning ">Planning du sport : {{sport.nom}} </h1>
<a class=" arrow " href="{{ path('AllSports')}}"> < </a>
 

<div>

<p class=" description "> {{sport.description}} </p>
<img class="imagePlanning" src="{{asset( sport.img )}}" alt="sport">

</div>

<div class="horaires">

<ul>

{% for h in horaires %}
        <li>
                <article> 
                    <h2>{{ h.jour }}</h2>
                    <p> {{ h.heure }} </p>
                    {% if not app.user %}
                    <button class="buttonPlanning" > <a  href="{{ path('security_login')}}">  Connectez-vous pour reserver  </a> </button>
                    {%else%}
                    <button class="buttonPlanning" > <a  href="{{ path('panier_add', { idHoraire: h.id, idUser: app.user.id })}}">  Reserver  </a> </button>
                    {%endif%}
                
                </article>
        </li>
{% endfor %}

</ul>


</div>
</section>



 <footer> 
        <p> Ce site est un projet purement personnel d'entrainement au framework Symfony </p>
        <p> This is a fully personnal project made for training the Symfony framework</p>
         <a href="{{ path('admin')}}">  Administration  </a>

    </footer>



    {% endblock %}

symfonyProject/templates/default/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre profil{% endblock %}

{% block body %}

<header class="secondary">
<div>

<h1> Sport Escape </h1>

<ul> 

<li> <a href="{{ path('home')}}"> Accueil </a> </li>
<li> <a href="{{ path('AllSports')}}"> Voir les sports </a> </li>
<li> <a href="{{ path('panier_index')}}">Votre panier</a> </li>
{% if not app.user %}
<li> <a href="{{ path('security_login')}}">  Se connecter  </a> </li>
 <li><a href="{{ path('security_registration')}}">  Creer un compte </a> </li> 
{% else %}
<li> <a href="{{ path('profil', {'idUser': app.user.id } )}}">Votre profil</a> </li>
<li> <a href="{{ path('security_logout')}}"> Se deconnecter  </a> </li>
{% endif %}
</ul>
 </div>


</header>

{% if not app.user %}
<p> Vous devez être connecté pour avoir accés à cette page  <a href="{{ path('security_login')}}"  class="cartLink">  Se connecter  </a> </p>
{% else %}
    <section>

    {% if app.user.id != user.id %}
    <p>Une erreur est survenue  <a href="{{ path('home')}}"  class="cartLink">  Revenir à l'accueil  </a> </p>
    {% else %}  

       <div class="profil">
        <h2> Votre profil </h2>
        <h3> Bonjour ! Votre email : {{user.username}}</h3> 
       
       </div>
       {%if reservations is not empty and commandes is not empty %}
       <div class="panier_plein"> 

       
       

        <h3> Vos reservations : </h3>

        <table>
    <thead>
        <tr>
            <th>Horaire</th>
            <th>Commande correspondante </th>
            
            
        </tr>
    </thead>
    <tbody>
        {% for ttlesReservCommande in reservations %}
            {% for reserv in ttlesReservCommande %}
                <tr>
                <td>{{ reserv.idHoraire}} </td>
                <td>{{ reserv.idCommande}}</td>
                </tr>
            {%endfor%}
        {%endfor%}
    </tbody>
</table>


<h3> Vos commandes : </h3>

        <table>
    <thead>
        <tr>
            <th>Numero</th>
            <th>Date</th>
            <th>Prix total</th>
            
            
            
        </tr>
    </thead>
    <tbody>
        
            {% for c in commandes %}
                <tr>
                <td>{{ c.id}}</td>
                <td>{{ c.date}}</td>
                <td>{{ c.Prix}} € </td>
                
                </tr>
            {%endfor%}
       
    </tbody>
</table>

        {% else %}

        <section class="panier_vide"> 

        <p> Vous n'avez aucune reservations </p>

        </section>


       
       </div>
       {% endif %}

    </section>



   <footer> 
        <p> Ce site est un projet purement personnel d'entrainement au framework Symfony </p>
        <p> This is a fully personnal project made for training the Symfony framework</p>
         <a href="{{ path('admin')}}">  Administration  </a>

    </footer>



{% endif %}
{% endif %}
{% endblock %}

symfonyProject/templates/default/sports.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous les sports {% endblock %}

{% block body %}


<header class="secondary">
<div>

<h1> Sport Escape </h1>

<ul> 

<li> <a href="{{ path('home')}}"> Accueil </a> </li>
<li> <a href="{{ path('AllSports')}}"> Voir les sports </a> </li>
<li> <a href="{{ path('panier_index')}}">Votre panier</a> </li>
{% if not app.user %}
<li> <a href="{{ path('security_login')}}">  Se connecter  </a> </li>
 <li><a href="{{ path('security_registration')}}">  Creer un compte </a> </li> 
{% else %}
<li> <a href="{{ path('profil', {'idUser': app.user.id } )}}">Votre profil</a> </li>
<li> <a href="{{ path('security_logout')}}"> Se deconnecter  </a> </li>
{% endif %}
</ul>
 </div>


</header>

<h1>Nos sports</h1>

<div class="listesSports">


<ul>

{% for s in AllSports %}
        <li>
            <a href="{{ path('planning', {'id': s.id } )}}">
                 
                    <h2> {{ s.nom }}</h2>
                    <img src="{{ asset( s.img )}}" alt="sport" class="sport">
                    <p> {{ s.description }} </p>

                
            </a>
        </li>
{% endfor %}

</ul>




</div>


 <footer> 
        <p> Ce site est un projet purement personnel d'entrainement au framework Symfony </p>
        <p> This is a fully personnal project made for training the Symfony framework</p>
         <a href="{{ path('admin')}}">  Administration  </a>

    </footer>




    {% endblock %}